"""Add allow_interruptions and timer fields

Revision ID: 9103068c50bc
Revises: 950771b549ce
Create Date: 2026-07-27 20:01:48.490408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9103068c50bc'
down_revision: Union[str, Sequence[str], None] = '950771b549ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_results', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('test_results', sa.Column('time_spent_seconds', sa.Integer(), nullable=True))
    op.add_column('tests', sa.Column('allow_interruptions', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'allow_interruptions')
    op.drop_column('test_results', 'time_spent_seconds')
    op.drop_column('test_results', 'started_at')
    # ### end Alembic commands ###
