"""Add test attempt/time/exam fields

Revision ID: 950771b549ce
Revises: 
Create Date: 2026-07-27 19:48:57.873782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '950771b549ce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('max_attempts', sa.Integer(), nullable=True))
    op.add_column('tests', sa.Column('time_limit_minutes', sa.Integer(), nullable=True))
    op.add_column('tests', sa.Column('exam_start', sa.DateTime(), nullable=True))
    op.add_column('tests', sa.Column('exam_end', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'exam_end')
    op.drop_column('tests', 'exam_start')
    op.drop_column('tests', 'time_limit_minutes')
    op.drop_column('tests', 'max_attempts')
    # ### end Alembic commands ###
