from dto_schemas.task import TaskBase, TaskResponse, TaskCreate, TaskCreateRequest, TaskUpdateRequest
from dto_schemas.answer import AnswerSubmitRequest, AnswerResponse, TestAnswerSubmission, SaveProgressRequest, SavedAnswerItem, SaveProgressResponse
from dto_schemas.test import TestCreate, TestCreateRequest, TestResponse, TestResultResponse
from dto_schemas.user import UserRegister, UserResponse, UserUpdate, ForgotPasswordRequest, ResetPasswordRequest, AssignStudentRequest, LoginResponse, TokenVerifyResponse, MessageResponse
from dto_schemas.stats import (
    UserStats, UserResponseWithStats,
    DailyStatsItem, PeriodStatsResponse,
    TopicSectionItem, TopicSummaryItem, TopicItem, TopicsStatsResponse,
    DifficultyItem, DifficultyStatsResponse, FullStatsResponse,
)
from dto_schemas.email import AllowedEmailBase, AllowedEmailCreate, AllowedEmailResponse
from dto_schemas.image import ImageUploadRequest, ImageUploadResponse
from dto_schemas.assignment import (
    TestAssignmentCreate, TestAssignmentResponse, StudentAssignmentResponse,
    TestGroupAssignment, GroupCreateRequest, GroupUpdateRequest,
    AddStudentsToGroupRequest
)
from dto_schemas.theory import TheoryBase, TheoryCreate, TheoryUpdate, TheoryResponse
from dto_schemas.ai import AITestRequest, TeacherAITestRequest, TheoryQuestionRequest
from dto_schemas.admin import (
    ChangeUserRoleRequest, SendTaskToTgRequest, AllowedEmailItemResponse,
    RebuildTestsResponse, RecomputeAnswersResponse,
    BatchTaskCreateItem, BatchTaskCreateRequest, BatchTaskCreateResponse,
    BatchTaskUpdateItem, BatchTaskUpdateRequest, BatchTaskUpdateResponse,
    BatchTaskDeleteRequest, BatchTaskDeleteResponse,
    ClassifyTasksRequest, ClassifyTasksResponse,
)
from dto_schemas.cached import (
    TaskShortResponse,
    TestSummaryResponse,
    StudentHistoryItemResponse,
    DifficultyStatResponse,
    ResultUserResponse,
    DetailedResultDetailResponse,
    DetailedResultResponse,
    StudentAssignmentItemResponse,
    StudentAssignmentMetaItemResponse,
    StudentAITestItemResponse,
    AvailableTestMetaResponse,
    TheoryTopicSummaryResponse,
    TheorySectionSummaryResponse,
    TeacherGroupStudentResponse,
    TeacherGroupResponse,
    TeacherHistoryResultResponse,
    TeacherHistoryItemResponse,
    TeacherAssignmentItemResponse,
    TaskGroupedResponse,
    TaskClassTopicMetaResponse,
    TopicSectionMetaResponse,
    TeacherTaskMetaByTopicSectionResponse,
    TeacherTaskMetaResponse,
    TeacherTaskSectionResponse,
    TeacherTasksByClassTopicResponse,
    TeacherStudentProfileResponse,
    TestCacheResponse,
    UserCacheResponse,
    GroupAssignResponse,
    AddStudentsToGroupResponse,
    TeacherTaskDetailResponse,
    StartTestTaskItem,
    StartAssignedTestResponse,
    RetakeTestResponse,
    SubmitTestResponse,
    AIHintContext,
    AIHintResponse,
    AISolutionContext,
    AISolutionResponse,
    AITheoryContext,
    AITheoryResponse,
)

from dto_schemas.schedule import (
    ParentCreate, ParentUpdate, ParentResponse,
    ScheduleCreate, ScheduleUpdate, ScheduleResponse,
    LessonCreate, LessonReschedule, LessonUpdate, LessonResponse,
    PaymentCreate, PaymentUpdate, PaymentResponse,
    CalendarDayResponse, CalendarResponse,
    TelegramPaymentRequest, TelegramPaymentResponse,
    TelegramWhoamiResponse, TelegramStudentBrief,
    TelegramBalanceResponse, TelegramPaymentBrief,
    TelegramPaymentStatsResponse,
)

__all__ = [
    "TaskBase", "TaskResponse", "TaskCreate", "TaskCreateRequest", "TaskUpdateRequest",
    "AnswerSubmitRequest", "AnswerResponse", "TestAnswerSubmission",
    "SaveProgressRequest", "SavedAnswerItem", "SaveProgressResponse",
    "TestCreate", "TestCreateRequest", "TestResponse", "TestResultResponse",
    "UserRegister", "UserResponse", "UserUpdate",
    "ForgotPasswordRequest", "ResetPasswordRequest", "AssignStudentRequest",
    "LoginResponse", "TokenVerifyResponse", "MessageResponse",
    "UserStats", "UserResponseWithStats",
    "DailyStatsItem", "PeriodStatsResponse",
    "TopicSectionItem", "TopicSummaryItem", "TopicItem", "TopicsStatsResponse",
    "DifficultyItem", "DifficultyStatsResponse", "FullStatsResponse",
    "AllowedEmailBase", "AllowedEmailCreate", "AllowedEmailResponse",
    "ImageUploadRequest", "ImageUploadResponse",
    "TestAssignmentCreate", "TestAssignmentResponse", "StudentAssignmentResponse", "TestGroupAssignment",
    "GroupCreateRequest", "GroupUpdateRequest", "AddStudentsToGroupRequest",
    "TheoryBase", "TheoryCreate", "TheoryUpdate", "TheoryResponse",
    "AITestRequest", "TeacherAITestRequest", "TheoryQuestionRequest",
    "ChangeUserRoleRequest", "SendTaskToTgRequest",
    "AllowedEmailItemResponse", "RebuildTestsResponse", "RecomputeAnswersResponse",
    "BatchTaskCreateItem", "BatchTaskCreateRequest", "BatchTaskCreateResponse",
    "BatchTaskUpdateItem", "BatchTaskUpdateRequest", "BatchTaskUpdateResponse",
    "BatchTaskDeleteRequest", "BatchTaskDeleteResponse",
    "ClassifyTasksRequest", "ClassifyTasksResponse",
    "TaskShortResponse", "TestSummaryResponse", "StudentHistoryItemResponse",
    "DifficultyStatResponse", "ResultUserResponse", "DetailedResultDetailResponse",
    "DetailedResultResponse", "StudentAssignmentItemResponse", "StudentAssignmentMetaItemResponse",
    "StudentAITestItemResponse", "AvailableTestMetaResponse", "TheoryTopicSummaryResponse", "TheorySectionSummaryResponse",
    "TeacherGroupStudentResponse", "TeacherGroupResponse", "TeacherHistoryResultResponse",
    "TeacherHistoryItemResponse", "TeacherAssignmentItemResponse", "TaskGroupedResponse",
    "TaskClassTopicMetaResponse", "TopicSectionMetaResponse", "TeacherTaskMetaByTopicSectionResponse",
    "TeacherTaskMetaResponse", "TeacherTaskSectionResponse", "TeacherTasksByClassTopicResponse",
    "TeacherStudentProfileResponse", "TestCacheResponse", "UserCacheResponse",
    "GroupAssignResponse", "AddStudentsToGroupResponse", "TeacherTaskDetailResponse",
    "StartTestTaskItem", "StartAssignedTestResponse", "RetakeTestResponse", "SubmitTestResponse",
    "AIHintContext", "AIHintResponse", "AISolutionContext", "AISolutionResponse",
    "AITheoryContext", "AITheoryResponse",
    # Schedule / Payments / Telegram
    "ParentCreate", "ParentUpdate", "ParentResponse",
    "ScheduleCreate", "ScheduleUpdate", "ScheduleResponse",
    "LessonCreate", "LessonReschedule", "LessonUpdate", "LessonResponse",
    "PaymentCreate", "PaymentUpdate", "PaymentResponse",
    "CalendarDayResponse", "CalendarResponse",
    "TelegramPaymentRequest", "TelegramPaymentResponse",
    "TelegramWhoamiResponse", "TelegramStudentBrief",
    "TelegramBalanceResponse", "TelegramPaymentBrief",
    "TelegramPaymentStatsResponse",
]